from cards import B, C, Section, Unit

UNIT = Unit(7, "Oscillations", [
    Section("7.1", "Defining Simple Harmonic Motion", [
        B(r"What condition on the force makes motion <b>simple harmonic</b>?",
          r"The restoring force is <b>proportional to the displacement</b> from equilibrium and points "
          r"<b>opposite</b> to it: \(F = -kx\)."),
        B(r"What is the <b>equilibrium position</b> of an oscillator?",
          r"The position where the <b>net force is zero</b>."),
        B(r"What is the <b>amplitude</b> of an oscillation?",
          r"The <b>maximum displacement</b> from equilibrium."),
        B(r"Where is a mass–spring oscillator moving <b>fastest</b>?",
          r"At the <b>equilibrium position</b> (\(x = 0\)).", bd="shm_spring"),
        B(r"Where is the <b>acceleration</b> of a mass–spring oscillator greatest?",
          r"At the <b>turning points</b> \(x = \pm A\), pointing toward equilibrium.", bd="shm_spring"),
        B(r"What is the acceleration of a mass–spring oscillator as it passes through equilibrium?",
          r"<b>Zero</b>. The net force is zero there."),
        B(r"Is a pendulum a simple harmonic oscillator?",
          r"<b>Approximately</b>, for small angles.",
          extra=r"The restoring force \(mg\sin\theta \approx mg\theta\) is roughly proportional to the "
                r"displacement only when \(\theta\) is small."),
        B(r"A ball bounces elastically on a floor forever. Is this simple harmonic motion?",
          r"<b>No.</b> It's periodic, but the force (constant gravity) is not proportional to the displacement."),
        B(r"Hanging a spring vertically instead of horizontally changes what about the oscillation?",
          r"Only the <b>equilibrium position</b>, which shifts down by \(mg/k\). The period stays \(2\pi\sqrt{m/k}\)."),
    ]),

    Section("7.2", "Frequency and Period of SHM", [
        C(r"Period and frequency: \(T = {{c1::\dfrac{1}{f}}}\)", tags=["formula"]),
        B(r"What is the SI unit of frequency?",
          r"The hertz: \(1\text{ Hz} = 1\text{ s}^{-1}\) (one cycle per second)"),
        C(r"Period of a mass–spring system: \(T_s = {{c1::2\pi\sqrt{\dfrac{m}{k}}}}\)", tags=["formula"]),
        C(r"Period of a simple pendulum (small angles): \(T_p = {{c1::2\pi\sqrt{\dfrac{L}{g}}}}\)",
          d="pendulum", tags=["formula"]),
        B(r"Does the period of a simple harmonic oscillator depend on its amplitude?",
          r"<b>No.</b>",
          extra=r"A larger amplitude means a longer path, but the oscillator also moves faster, and the "
                r"two effects cancel."),
        B(r"Does a pendulum's period depend on the mass of the bob?",
          r"<b>No.</b> \(T = 2\pi\sqrt{L/g}\)."),
        B(r"If the mass on a spring is made <b>4×</b> larger, what happens to the period?",
          r"It <b>doubles</b> (\(T \propto \sqrt m\))."),
        B(r"How does a pendulum's period on the Moon (\(g_M \approx g/6\)) compare to its period on Earth?",
          r"<b>Longer</b>, by a factor of \(\sqrt6 \approx 2.4\)."),
        B(r"A pendulum hangs in an elevator that accelerates <b>upward</b>. Does its period get longer or shorter?",
          r"<b>Shorter</b>. The effective gravity is \(g + a\), which is larger."),
        B(r"Find the period of a \(1\text{ kg}\) mass on a spring with \(k = 100\text{ N/m}\).",
          r"\(T = 2\pi\sqrt{1/100} \approx 0.63\text{ s}\)", tags=["problem"]),
    ]),

    Section("7.3", "Representing and Analyzing SHM", [
        C(r"Position of an oscillator released from rest at \(x = A\) at \(t = 0\): "
          r"\(x(t) = {{c1::A\cos(2\pi ft)}}\)", tags=["formula"],
          extra=r"If it starts at equilibrium moving in the + direction, \(x = A\sin(2\pi ft)\)."),
        B(r"In SHM, what is the velocity at the instant the displacement is at its maximum?",
          r"<b>Zero</b>.", bd="shm_graphs"),
        B(r"In SHM, how is the direction of the acceleration related to the displacement?",
          r"<b>Always opposite</b>: \(a = -\omega^2x\).", bd="shm_graphs"),
        C(r"Maximum speed in SHM: \(v_{max} = {{c1::A\omega}}\), where \(\omega = 2\pi f\)", tags=["formula"]),
        C(r"Maximum acceleration in SHM: \(a_{max} = {{c1::A\omega^2}}\), where \(\omega = 2\pi f\)",
          tags=["formula"]),
        B(r"What does a graph of acceleration vs. position look like for SHM?",
          r"A <b>straight line through the origin with negative slope</b>.",
          extra=r"The slope is \(-\omega^2 = -k/m\)."),
        C(r"Angular frequency of a mass–spring oscillator: \(\omega = {{c1::\sqrt{k/m}}}\)", tags=["formula"]),
    ]),

    Section("7.4", "Energy of Simple Harmonic Oscillators", [
        C(r"Total energy of a mass–spring oscillator with amplitude \(A\): \(E = {{c1::\tfrac12kA^2}}\)",
          tags=["formula"]),
        B(r"Where is all of a mass–spring oscillator's energy potential, and where is it all kinetic?",
          r"All potential at the turning points \(x = \pm A\). All kinetic at equilibrium \(x = 0\).",
          bd="shm_energy",
          extra=r"\(K + U\) stays constant throughout."),
        B(r"What is the speed of a mass–spring oscillator at position \(x\)?",
          r"\[v = \sqrt{\frac{k}{m}\left(A^2 - x^2\right)}\]",
          extra=r"From \(\tfrac12kA^2 = \tfrac12mv^2 + \tfrac12kx^2\)."),
        B(r"At what position is \(K = U\) for a mass–spring oscillator?",
          r"\(x = \pm\dfrac{A}{\sqrt2} \approx \pm0.71A\)", tags=["problem"]),
        B(r"If an oscillator's amplitude doubles, what happens to its total energy?",
          r"It becomes <b>4×</b> as large (\(E \propto A^2\))."),
        B(r"If an oscillator's amplitude doubles, what happens to its maximum speed?",
          r"It <b>doubles</b> (\(v_{max} = A\omega\))."),
        B(r"A pendulum is released from height \(h\) above its lowest point. What is its maximum speed?",
          r"\(v_{max} = \sqrt{2gh}\), reached at the bottom."),
        B(r"A spring with \(k = 200\text{ N/m}\) oscillates with amplitude \(0.1\text{ m}\). What is the total energy?",
          r"\(E = \tfrac12(200)(0.1)^2 = 1\text{ J}\)", tags=["problem"]),
        B(r"A \(0.5\text{ kg}\) mass oscillates on a spring with total energy \(1\text{ J}\). What is its maximum speed?",
          r"\(v_{max} = \sqrt{2E/m} = 2\text{ m/s}\)", tags=["problem"]),
    ]),
])
